const todosAPI = (() => {
  const TODO_API = "http://localhost:3000/todos";

  // GET
  const getAll = async () => {
    const response = await fetch(TODO_API);
    const todos = await response.json();
    return todos;
  };

  // POST
  const add = async (newTodo) => {
    const res = await fetch(TODO_API, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(newTodo),
    });
    const todo = await res.json();
    // we need the id of the new todo
    // because id should be generated by the server
    return todo;
  };

  const edit = async (id, updatedTodo) => {
    await fetch(`${TODO_API}/${id}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(updatedTodo),
    });
  };

  // DELETE
  const deleteById = async (id) => {
    await fetch(`${TODO_API}/${id}`, {
      method: "DELETE",
    });
  };

  return {
    getAll,
    add,
    edit,
    deleteById,
  };
})();


