import { NewTodo } from "./reducers/todosReducer";

const todosAPI = (() => {
  const TODO_API = "http://localhost:3000/todos";

  // GET
  const getAll = async () => {
    const response = await fetch(TODO_API);
    const todos = await response.json();
    return todos;
  };

  // POST
  const add = async (newTodo: NewTodo) => {
    const res = await fetch(TODO_API, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(newTodo),
    });
    const todo = await res.json();
    // we need the id of the new todo
    // because id should be generated by the server
    return todo;
  };

  const toggle = async (id: number, newStatus: boolean) => {
    await fetch(`${TODO_API}/${id}`, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        completed: newStatus,
      }),
    });
  };

  // DELETE
  const deleteById = async (id: number) => {
    await fetch(`${TODO_API}/${id}`, {
      method: "DELETE",
    });
  };

  return {
    getAll,
    add,
    toggle,
    deleteById,
  };
})();

export default todosAPI;
